### ISSUE TITLE
How to get use Auth

### ISSUE THREAD

**Issue by scharinger** [Granipouss/firevuex#1]
Hi! 
I like you tool so far, thank you! I'm using the database and it work fine. Now I would like to get started with the auth, but I'm getting an error of `auth/signInWithEmailAndPassword` not being an action available.
This is how I thought it should work by reading the [source](https://github.com/Granipouss/firevuex/blob/master/src/auth.js):
![image](https://cloud.githubusercontent.com/assets/724211/23237894/ba304d2c-f95f-11e6-900b-9ecc4acdf540.png)
![image](https://cloud.githubusercontent.com/assets/724211/23237912/d2001e28-f95f-11e6-9bf4-eb97e32b7ea6.png)
![image](https://cloud.githubusercontent.com/assets/724211/23238062/7f1c73b8-f960-11e6-9ce8-1fb9ffa4de3a.png)
It seems as the store gets the getters for the user at least. Here I've logged in with the console:
![image](https://cloud.githubusercontent.com/assets/724211/23238152/e3fbe9d0-f960-11e6-8ede-95ad2186f426.png)
I exposed the firebase app object to the stores state in `fb` for testing (rather ugly):
![image](https://cloud.githubusercontent.com/assets/724211/23238204/2bda0cc8-f961-11e6-9074-716649d319cf.png)

**Comment by Granipouss** [comment]
Hey !
It nice to see that it is useful to someonne. 
Actually, the auth module was kinda experimental, and I had forgotten to build it in the previous release.
I fixed it here 88bb422cf895bf04af8d8603ffe339f73b7a6210

I hope that it will solve your issues.
I also have had an example for auth.

Cheers.

**Comment by scharinger** [comment]
@Granipouss, thank you so much for your help and fast answer! It works fine now 👍
